### ISSUE TITLE
Ability to take control of the change

### ISSUE THREAD

**Issue by victorpavlenko** [EitanElbaz/ReactGrandTour#3]
It was just as great to get control of step changes:
`onStepChange`

For example, if I want to change the page after a certain step, using react-router history. Is not possible now

**Comment by EitanElbaz** [comment]
> Also if its possible to skip for mobile or specific media width ?

I think that's out of scope for the library. I would suggest you filter out steps using some sort of media query.

I use Material-UI in most of my projects which contains lots of useful hooks for responsive UIs.

A library like this could help you with deciding which steps should be included:

https://github.com/contra/react-responsive#with-hooks
