### ISSUE TITLE
On small screen modal is clipped and does not change position

### ISSUE THREAD

**Issue by victorpavlenko** [EitanElbaz/ReactGrandTour#5]
On small screen like tablet 
![image](https://user-images.githubusercontent.com/5157416/138308786-df59999a-c64c-4f05-bd5d-de739313652c.png)

It would be great to have this option inside **ReactGrandTourStep** like position: **top, left, right, bottom**

Or much better if determines the position automatically

**Comment by EitanElbaz** [comment]
I can't tell exactly what's going wrong.

The position is already calculated automatically to the best of its ability.

Are you asking for an option for a preferred of the modal per step?

**Comment by EitanElbaz** [comment]
@victorpavlenko - I've started working on it here and I'm hoping it won't be much longer.

https://github.com/EitanElbaz/ReactGrandTour/tree/feature/%235_prefered_position

**Comment by EitanElbaz** [comment]
> @victorpavlenko - I will try to look at adding a preferred position per step.
> 
> What do you think about this for each step?
> 
> ```js
> preferredModalPosition?: 'auto' | 'top' | 'right' | 'bottom' | 'left';
> ```

@victorpavlenko the thing this doesn't allow for is saying something like...

`I would prefer position left, but if there is no space, then position right.`

In my experimental branch, this is the order: 

Check if preferred position fits. If it fits position it there.

If it doesn't fit, then set the preferred position to `auto`.

When the position is set to `auto`, it then goes in this order to position the modal:

1. right
2. left
3. top
4. bottom

------

Using the example above, if I set preferred position to `bottom`, but there wasn't space underneath, and there was space on the right, it would position it on the right.

In reality though I may have wanted it to fall back to position `top` if there wasn't space on the bottom.

Does that make sense?

And how much do you think it will matter if there is no fallback setting?

**Comment by EitanElbaz** [comment]
One possibility is making the prop an array, so you place your preferred positions in order. What do you think?

**Comment by victorpavlenko** [comment]
![image](https://user-images.githubusercontent.com/5157416/140328860-75104db2-3e25-4b2b-9b07-63d699844a7f.png)

I think that the main problem is that you calculate the dimensions based on the dimensions of the window and not the element that is limited in height.

To simulate this just add a couple of css properties. As in the screenshot.

**Comment by EitanElbaz** [comment]
> ![image](https://user-images.githubusercontent.com/5157416/140328860-75104db2-3e25-4b2b-9b07-63d699844a7f.png)
> 
> 
> 
> I think that the main problem is that you calculate the dimensions based on the dimensions of the window and not the element that is limited in height.
> 
> 
> 
> To simulate this just add a couple of css properties. As in the screenshot.

I think you misunderstood my question. Positioning the modal in the window is intentional.

I basically have it working where you can choose you're preferred position, but you can't pick a backup. In the feature branch, if your preferred position isn't possible it just goes back to automatic mode. Is that acceptable?

**Comment by victorpavlenko** [comment]
@EitanElbaz if u give me ur mail I can send ur app example and u can see the problem

**Comment by EitanElbaz** [comment]
I can't position the modal relative to the element being focused because that would probably involve having to modify the DOM around that element which could mess up layout and styling.

I think this is going a bit off topic though. 

I think having a single preference for a modal position is probably good enough so I might just release that change in the morning.

If you'd like to raise a new issue then a simplified codepen example would be really helpful

**Comment by victorpavlenko** [comment]
@EitanElbaz hey! Did u release this staff ?

**Comment by EitanElbaz** [comment]
Get back from holiday today so will release it soon

**Comment by EitanElbaz** [comment]
I have released v0.8.0 which allows you to pick a preferred position

https://github.com/EitanElbaz/ReactGrandTour/releases/tag/0.8.0

**Comment by victorpavlenko** [comment]
Amazing this work
